### ISSUE TITLE
test file structure 

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI_524_Group2_Python#42]
should we add all our tests into test_pyb4model.py or create a separate file for each of our tests?

**Comment by eyrakas** [comment]
I think both should be okay. Did tiffany suggest any preference?

**Comment by andrealee011** [comment]
Yep, both are fine! We just needed to decide on which one we want to do as I noticed we had a main test function and separate test functions

**Comment by andrealee011** [comment]
Jake and I think we should just stick to one main function as that’s what cookie cutter created

**Comment by eyrakas** [comment]
I agree. Let's do it that way for consistency with the cookie cutter.
