### ISSUE TITLE
add code coverage button to readme

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI_524_Group2_Python#59]
The coverage should be communicated by a codecov.io button on your package GitHub repository README's.

**Comment by andrealee011** [comment]
'Revisit your test cases and add additional test cases, if required, in your Python and R packages. At the end of this milestone, we want you to have 90% branch coverage (or higher!). The coverage should be communicated by a codecov.io button on your package GitHub repository README's.'

**Comment by agdal1125** [comment]
I did this. Don't worry about it
